### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vagrant1991** [liaohuqiu/android-cube-app#10]
E/AndroidRuntime(28784): java.lang.RuntimeException: Unable to start activity ComponentInfo{in.srain.cube.demo/in.srain.cube.demo.base.DemoHomeActivity}: android.view.InflateException: Binary XML file line #6: Error inflating class in.srain.cube.views.ptr.PtrFrameLayout

**Comment by liaohuqiu** [comment]
You should clean your resource.
