### ISSUE TITLE
用IDEA 导入工程没有成功。

### ISSUE THREAD

**Issue by comk** [liaohuqiu/android-cube-app#2]
首先，非常感谢你的开源项目，希望从你的开源项目中学到更多的东西。
不知道是版本问题还是什么原因，我导入工程无法通过编译。
我也是首次使用IDEA这个开发工具。
不知道哪里设置不正确而导致项目编译无法通过。
例如：import in.srain.cube.mints.base.MintsBaseActivity;  MintsBaseActivity这个类导入失败。
希望给我一些提示。再次感谢你的开源项目。谢谢

**Comment by comk** [comment]
![qq 20150106090920](https://cloud.githubusercontent.com/assets/5652883/5622781/e32782fa-9583-11e4-99c7-634cd827c4b4.png)

**Comment by liaohuqiu** [comment]
`pom.xml` 内没有 `snapshot` 的库地址，部分 `snapshot` 包没有下载下来。
